import { AlertCircle, BarChart3, Boxes, ClipboardCheck, Factory, FileText, Package, Settings, Shield, ShoppingCart, Truck, Users, Wallet } from 'lucide-react'
import { ROLES } from './rolePermissions'

export const sidebarConfig = {
  [ROLES.ADMIN]: [
    { label: 'Dashboard', path: '/dashboard/admin', icon: BarChart3 },
    { label: 'User Management', path: '/masters/users', icon: Users },
    { label: 'Role & Permission', path: '/masters/permissions', icon: Shield },
    { label: 'Employee Master', path: '/masters/employees', icon: Users },
    { label: 'Customer / Supplier Master', path: '/masters/customers-suppliers', icon: Users },
    { label: 'Item Master', path: '/masters/items', icon: Boxes },
    { label: 'Warehouse / Location', path: '/masters/warehouses', icon: Package },
    { label: 'Machine / Work Center', path: '/masters/machines', icon: Factory },
    { label: 'BOM / Recipe', path: '/production/bom', icon: Boxes },
    { label: 'BOM Approvals', path: '/production/bom-approvals', icon: ClipboardCheck },
    { label: 'Finished Goods Inventory', path: '/inventory/finished-goods', icon: Package },
    { label: 'Waste Management', path: '/qc/wastage', icon: AlertCircle },
    { label: 'System Settings', path: '/masters/settings', icon: Settings },
    { label: 'Audit Logs', path: '/reports/audit-logs', icon: FileText },
  ],
  [ROLES.CEO]: [
    { label: 'CEO Dashboard', path: '/dashboard/ceo', icon: BarChart3 },
    { label: 'Sales Overview', path: '/sales/overview', icon: ShoppingCart },
    { label: 'Production Overview', path: '/production/overview', icon: Factory },
    { label: 'Inventory Overview', path: '/inventory/overview', icon: Package },
    { label: 'QC & Rejection Report', path: '/qc/reports', icon: ClipboardCheck },
    { label: 'Dispatch Overview', path: '/dispatch/overview', icon: Truck },
  ],
  [ROLES.SALES]: [
    { label: 'Sales Dashboard', path: '/dashboard/sales', icon: BarChart3 },
    { label: 'Customers', path: '/sales/customers', icon: Users },
    { label: 'Sales Orders', path: '/sales/orders', icon: ShoppingCart },
    { label: 'Finished Goods Availability', path: '/inventory/finished-goods', icon: Package },
    { label: 'Order Status Tracking', path: '/sales/tracking', icon: FileText },
    { label: 'Dispatch Status', path: '/dispatch/history', icon: Truck },
    { label: 'Invoice Status', path: '/billing/invoices', icon: Wallet },
  ],
  [ROLES.PRODUCTION_MANAGER]: [
    { label: 'Production Dashboard', path: '/dashboard/production', icon: BarChart3 },
    { label: 'Production Requirements', path: '/production/requirements', icon: FileText },
    { label: 'Daily Production Planning', path: '/production/planning', icon: Factory },
    { label: 'BOM / Recipe', path: '/production/bom', icon: Boxes },
    { label: 'Machine Availability', path: '/masters/machines', icon: Factory },
    { label: 'Material Availability', path: '/inventory/raw-material', icon: Package },
    { label: 'Waste Management', path: '/qc/wastage', icon: AlertCircle },
    { label: 'Production Orders / Batches', path: '/production/orders', icon: ClipboardCheck },
    { label: 'Plan Approvals', path: '/production/plan-approvals', icon: AlertCircle },
    { label: 'Production Reports', path: '/reports/production', icon: BarChart3 },
  ],
  [ROLES.STOCK_MANAGER]: [
    { label: 'Inventory Dashboard', path: '/dashboard/inventory', icon: BarChart3 },
    { label: 'Stock Ledger', path: '/inventory/ledger', icon: FileText },
    { label: 'Raw Material Stock', path: '/inventory/raw-material', icon: Package },
    { label: 'Packing Material Stock', path: '/inventory/packing-material', icon: Package },
    { label: 'Finished Goods Inventory', path: '/inventory/finished-goods', icon: Package },
    { label: 'Material Reservation', path: '/inventory/reservation', icon: Boxes },
    { label: 'Material Issue', path: '/inventory/issue', icon: Boxes },
    { label: 'Warehouse Transfer', path: '/inventory/transfer', icon: Truck },
    { label: 'Stock Adjustment', path: '/inventory/adjustment', icon: Settings },
    { label: 'Low Stock Alerts', path: '/inventory/alerts', icon: AlertCircle },
  ],
  [ROLES.SUPERVISOR]: [
    { label: 'Supervisor Dashboard', path: '/dashboard/supervisor', icon: BarChart3 },
    { label: 'Assigned Production Orders', path: '/production/orders', icon: ClipboardCheck },
    { label: 'Material Received', path: '/inventory/issue', icon: Package },
    { label: 'Production Execution', path: '/production/execution', icon: Factory },
    { label: 'Downtime Entry', path: '/production/downtime', icon: AlertCircle },
    { label: 'Scrap / Wastage Entry', path: '/qc/wastage', icon: AlertCircle },
    { label: 'Send To QC', path: '/qc/inspection', icon: ClipboardCheck },
  ],
  [ROLES.OPERATOR]: [
    { label: 'My Dashboard', path: '/dashboard/operator', icon: BarChart3 },
    { label: 'My Assigned Operations', path: '/production/my-operations', icon: Factory },
    { label: 'Start / End Operation', path: '/production/execution', icon: ClipboardCheck },
    { label: 'Output Entry', path: '/production/output', icon: Boxes },
    { label: 'Downtime Entry', path: '/production/downtime', icon: AlertCircle },
    { label: 'My Productivity', path: '/reports/productivity', icon: BarChart3 },
  ],
  [ROLES.QC]: [
    { label: 'QC Dashboard', path: '/dashboard/qc', icon: BarChart3 },
    { label: 'Pending QC', path: '/qc/pending', icon: ClipboardCheck },
    { label: 'In Inspection', path: '/qc/inspection', icon: ClipboardCheck },
    { label: 'QC Checklist', path: '/qc/checklist', icon: FileText },
    { label: 'Approved Batches', path: '/qc/approved', icon: ClipboardCheck },
    { label: 'Rejected Batches', path: '/qc/rejected', icon: AlertCircle },
    { label: 'Rework Batches', path: '/qc/rework', icon: AlertCircle },
    { label: 'Waste Management', path: '/qc/wastage', icon: AlertCircle },
    { label: 'QC Reports', path: '/qc/reports', icon: BarChart3 },
  ],
  [ROLES.PACKAGING]: [
    { label: 'Packaging Dashboard', path: '/dashboard/packaging', icon: BarChart3 },
    { label: 'Pending Packaging', path: '/packaging/pending', icon: Package },
    { label: 'Packing Material Availability', path: '/inventory/packing-material', icon: Package },
    { label: 'Packaging Entry', path: '/packaging/entry', icon: ClipboardCheck },
    { label: 'Packed Goods', path: '/packaging/packed', icon: Boxes },
    { label: 'Move To Finished Goods', path: '/packaging/move-fg', icon: Truck },
  ],
  [ROLES.DISPATCH]: [
    { label: 'Dispatch Dashboard', path: '/dashboard/dispatch', icon: BarChart3 },
    { label: 'Ready For Dispatch', path: '/dispatch/ready', icon: Truck },
    { label: 'Dispatch Planning', path: '/dispatch/planning', icon: FileText },
    { label: 'Picking List', path: '/dispatch/picking', icon: ClipboardCheck },
    { label: 'Vehicle Loading', path: '/dispatch/loading', icon: Truck },
    { label: 'Delivery Challan', path: '/dispatch/challan', icon: FileText },
    { label: 'Dispatch History', path: '/dispatch/history', icon: FileText },
  ],
  [ROLES.ACCOUNTS]: [
    { label: 'Billing Dashboard', path: '/dashboard/billing', icon: BarChart3 },
    { label: 'Pending Billing', path: '/billing/pending', icon: Wallet },
    { label: 'Invoice Generation', path: '/billing/invoices', icon: FileText },
    { label: 'Payment Tracking', path: '/billing/payments', icon: Wallet },
    { label: 'Outstanding Receivables', path: '/billing/receivables', icon: AlertCircle },
    { label: 'Customer Ledger', path: '/billing/ledger', icon: FileText },
    { label: 'Revenue Reports', path: '/reports/revenue', icon: BarChart3 },
  ],
}
